### ISSUE TITLE
bck2brwsr incompatible with AWS Cognito

### ISSUE THREAD

**Issue by eppleton** [jtulach/bck2brwsr#13] opened 2019-03-17 15:55 UTC
Trying to use Amazon Cognito SDK on the same webpage as bck2brwsr. When bck2brwsr isn't initialized, this code works fine:

```
var login = function (e) {
               
                var user = document.getElementById("username").value;
                var password = document.getElementById("password").value;
                var loginscreen = document.getElementById("loginscreen");
                var authenticationData = {
                    Username: user,
                    Password: password
                };
                var authenticationDetails = new AmazonCognitoIdentity.AuthenticationDetails(authenticationData);
                var poolData = {UserPoolId: 'eu-central-1_something',
                    ClientId: 'somethingsomething'
                };
                var userPool = new AmazonCognitoIdentity.CognitoUserPool(poolData);
                var userData = {
                    Username: user,
                    Pool: userPool
                };
                var cognitoUser = new AmazonCognitoIdentity.CognitoUser(userData);
                cognitoUser.authenticateUser(authenticationDetails, {
                    onSuccess: function (result) {
                        var accessToken = result.getAccessToken().getJwtToken();
                        // startBck2Brwsr(); <- this is my current workaround
                    },
                    onFailure: function (err) {
                        ko.dataFor(loginscreen).loginFailed();
                    }
                });
            }
```
When running with bck2brwsr I get a:

TypeError: undefined is not an object (evaluating 'this.config.params')

The object in question is a "this" reference inside aws-cognito-sdk.min.js . Inspecting the Object it is titled "java.lang.Object". 

It's probably difficult to test this from my description alone, but I can give you private access to the project.

**Comment by jtulach** [comment] 2019-03-29 12:13
I am afraid I can't reproduce the issue without further help. Closing.

**Closed by jtulach** 2019-03-29 12:13 UTC

**Comment by eppleton** [comment] 2019-03-29 15:19
I sent you information and gave you access to my private repo this morning with additional info for reproducing. If something is missing, let me know.

Von meinem iPad gesendet
